### ISSUE TITLE
Blacklisting & Custom objectives

### ISSUE THREAD

**Issue by FoxKilo** [Spearhead-Gaming-Milsim/Queens-Stallions#52]
Several reports of infantry/armor spawning within the walls of the base and at the ends of runways when the AI commander is launching a counter-attack or escalating it's response to player activity. Not sure if this is an issue with blacklisting, how that interacts with custom objectives and the CQB module. All look to be setup correctly.

Tested by expanding the blacklist marker to 4x it's size and still had enemy spawning at custom objectives and normal objective placement. Tested again without the custom objectives and nothing is spawning within the marker boundaries.

One for the back burner.

**Comment by coachwn** [comment]
Think we might want to delete the custom objectives in the northern part around the airfield to see what happens. With the OPCOM set to occupation it is going to not have things spawn but will still try to attack those areas but at a slower rate.

**Comment by coachwn** [comment]
Put me and Jerkin on this as assigned please.

**Comment by FoxKilo** [comment]
hotfix already implemented. Leaving this open for longer term investigation of how to overcome the custom objective issue.

**Comment by coachwn** [comment]
Will take a look when I get home this afternoon.

**Comment by coachwn** [comment]
Taking a look at the custom objectives priorities and force sizes. A lot of the priorities are set to 100 and the remainder are set to 50 with a huge response.

**Comment by coachwn** [comment]
Just found a marker on the map listed at Alive_mil_logistics and the force pool was set to infinite and the reinforcement was dynamic. Also it had airplanes and helicopters enabled in the reinforcement aspect. It had to be tossing errors to the OPCOM and conflicting information since those were not listed as something to be used. 

Also I just tweaked the Custom Objectives in my test to lower them to under 50 in the area around Zelenogorsk and over to just south of Novy. Also removed the custom objectives in the area around the airfield and added 2 x TAOR on the map and limited the AI to loading into those AO's. Going to see what happens there since they were spawning CQB AI all over the map as well.

**Comment by coachwn** [comment]
Closed.
